version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: product_catalog_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpwd"]
      interval: 10s
      retries: 5
    networks:
      - product_catalog_network

  redis:
    image: redis:7-alpine
    container_name: product_catalog_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redispwd
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      retries: 5
    networks:
      - product_catalog_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_catalog_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - product_catalog_network

volumes:
  db_data:
  redis_data:

networks:
  product_catalog_network:
    driver: bridge