version: "3.8"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: product_catalog_filebeat
    user: root
    command: filebeat -e --strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log/app:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
