# src/main/resources/application-docker.properties

# Database Configuration (MySQL in Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
